spring:
  application:
    name: flashdrop
  datasource:
    url: jdbc:postgresql://localhost:5433/flashdrop
    username: flashdrop
    password: flashdrop
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6380

server:
  port: 8080
  tomcat:
    accept-count: 500
    threads:
      max: 400
      min-spare: 50

flashdrop:
  rate-limit:
    capacity: 5
    refill-period-seconds: 10
